[package]
name = "program"
version = "0.1.0"
authors = ["Heiko Alexander Weber <heiko.a.weber@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.0"
redis = "0.12.0"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.40"
